In [11]:
import pandas as pd
import numpy as np
import torch 
import tensorflow as tf
import matplotlib as mpl
from matplotlib import pyplot as plt
import seaborn as sns

In [30]:
dataframes = []  # To store the imported data from each file

for i in range(1,61):
    file = f"Data/{i}.xlsx"
    df = pd.read_excel(file)  # Use pd.read_excel() for Excel files
    dataframes.append(df)
    print(file,dataframes)

Data/1.xlsx [       Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0  -0.961714  -2.247089   -4.40107
2             NaN   0.000977  -0.394591  -2.298639  -1.552597
3             NaN   0.001953   -5.44346   0.849591    5.49498
4             NaN    0.00293   -1.46255    0.77963   1.958311
...           ...        ...        ...        ...        ...
98812         NaN     96.495  -0.545578   0.021109   2.797396
98813         NaN     96.496  -2.762514   1.902683   2.955644
98814         NaN     96.497  -0.147856  -0.159316  -1.166176
98815         NaN     96.498   -0.75917  -0.464933   2.385214
98816         NaN     96.499  -2.386887   2.186207    1.56821

[98817 rows x 5 columns]]
Data/2.xlsx [       Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0  -0.961714  -2.247089   -4.40107
2             NaN   0.000977  -0.394591  -2.298639  -1.552597
3             NaN   0.001953   -5.44346   0.849591    5.49498
4             NaN    0.00293   -1.46255    0.77963   1.958311
...           ...        ...        ...        ...        ...
98812         NaN     96.495  -0.545578   0.021109   2.797396
98813         NaN     96.496  -2.762514   1.902683   2.955644
98814         NaN     96.497  -0.147856  -0.159316  -1.166176
98815         NaN     96.498   -0.75917  -0.464933   2.385214
98816         NaN     96.499  -2.386887   2.186207    1.56821

[98817 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -1.212132   1.217805   3.375187
2              NaN   0.000977  -1.370485   1.744351   2.039275
3              NaN   0.001953   3.089165   2.274579  -0.801837
4              NaN    0.00293   0.120975   1.409276   -0.48534
...            ...        ...        ...        ...        ...
102396         NaN     99.995  -1.112702   3.835806   0.504633
102397         NaN     99.996  -1.624585   1.118387  -2.656656
102398         NaN     99.997   1.258904   0.621298  -3.389016
102399         NaN     99.998  -1.897099    0.41878   1.406281
102400         NaN     99.999  -4.828463  -1.234501   4.313637

[102401 rows x 5 columns]]
Data/3.xlsx [       Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0  -0.961714  -2.247089   -4.40107
2             NaN   0.000977  -0.394591  -2.298639  -1.552597
3             NaN   0.001953   -5.44346   0.849591    5.49498
4             NaN    0.00293   -1.46255    0.77963   1.958311
...           ...        ...        ...        ...        ...
98812         NaN     96.495  -0.545578   0.021109   2.797396
98813         NaN     96.496  -2.762514   1.902683   2.955644
98814         NaN     96.497  -0.147856  -0.159316  -1.166176
98815         NaN     96.498   -0.75917  -0.464933   2.385214
98816         NaN     96.499  -2.386887   2.186207    1.56821

[98817 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -1.212132   1.217805   3.375187
2              NaN   0.000977  -1.370485   1.744351   2.039275
3              NaN   0.001953   3.089165   2.274579  -0.801837
4              NaN    0.00293   0.120975   1.409276   -0.48534
...            ...        ...        ...        ...        ...
102396         NaN     99.995  -1.112702   3.835806   0.504633
102397         NaN     99.996  -1.624585   1.118387  -2.656656
102398         NaN     99.997   1.258904   0.621298  -3.389016
102399         NaN     99.998  -1.897099    0.41878   1.406281
102400         NaN     99.999  -4.828463  -1.234501   4.313637

[102401 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -3.554277   0.234673   1.156028
2              NaN   0.000977  -3.035028  -0.895744   2.050316
3              NaN   0.001953  -1.016954   1.600747  -0.095239
4              NaN    0.00293   -2.09596  -1.227136  -1.821252
...            ...        ...        ...        ...        ...
103420         NaN        101  -1.492011  -0.461251  -1.902216
103421         NaN        101  -3.174967  -1.506979  -2.803864
103422         NaN        101  -2.710958  -1.168222  -0.606787
103423         NaN        101  -3.300176  -1.540118  -2.215033
103424         NaN        101  -1.550933  -0.059898  -2.649296

[103425 rows x 5 columns]]
Data/4.xlsx [       Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0  -0.961714  -2.247089   -4.40107
2             NaN   0.000977  -0.394591  -2.298639  -1.552597
3             NaN   0.001953   -5.44346   0.849591    5.49498
4             NaN    0.00293   -1.46255    0.77963   1.958311
...           ...        ...        ...        ...        ...
98812         NaN     96.495  -0.545578   0.021109   2.797396
98813         NaN     96.496  -2.762514   1.902683   2.955644
98814         NaN     96.497  -0.147856  -0.159316  -1.166176
98815         NaN     96.498   -0.75917  -0.464933   2.385214
98816         NaN     96.499  -2.386887   2.186207    1.56821

[98817 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -1.212132   1.217805   3.375187
2              NaN   0.000977  -1.370485   1.744351   2.039275
3              NaN   0.001953   3.089165   2.274579  -0.801837
4              NaN    0.00293   0.120975   1.409276   -0.48534
...            ...        ...        ...        ...        ...
102396         NaN     99.995  -1.112702   3.835806   0.504633
102397         NaN     99.996  -1.624585   1.118387  -2.656656
102398         NaN     99.997   1.258904   0.621298  -3.389016
102399         NaN     99.998  -1.897099    0.41878   1.406281
102400         NaN     99.999  -4.828463  -1.234501   4.313637

[102401 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -3.554277   0.234673   1.156028
2              NaN   0.000977  -3.035028  -0.895744   2.050316
3              NaN   0.001953  -1.016954   1.600747  -0.095239
4              NaN    0.00293   -2.09596  -1.227136  -1.821252
...            ...        ...        ...        ...        ...
103420         NaN        101  -1.492011  -0.461251  -1.902216
103421         NaN        101  -3.174967  -1.506979  -2.803864
103422         NaN        101  -2.710958  -1.168222  -0.606787
103423         NaN        101  -3.300176  -1.540118  -2.215033
103424         NaN        101  -1.550933  -0.059898  -2.649296

[103425 rows x 5 columns],        Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0   0.168849   3.180385   0.294862
2             NaN   0.000977  -0.854918    1.00424  -0.051077
3             NaN   0.001953  -1.525155   1.085248  -0.437497
4             NaN    0.00293  -1.466233   1.096294   2.385214
...           ...        ...        ...        ...        ...
97788         NaN     95.495  -0.950666  -0.612219  -2.619854
97789         NaN     95.496  -4.938941   0.124209   0.235979
97790         NaN     95.497  -1.414676   0.300952  -3.826959
97791         NaN     95.498  -1.992847  -1.090897  -1.136735
97792         NaN     95.499   -2.76988   1.195712  -0.720873

[97793 rows x 5 columns]]
Data/5.xlsx [       Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0  -0.961714  -2.247089   -4.40107
2             NaN   0.000977  -0.394591  -2.298639  -1.552597
3             NaN   0.001953   -5.44346   0.849591    5.49498
4             NaN    0.00293   -1.46255    0.77963   1.958311
...           ...        ...        ...        ...        ...
98812         NaN     96.495  -0.545578   0.021109   2.797396
98813         NaN     96.496  -2.762514   1.902683   2.955644
98814         NaN     96.497  -0.147856  -0.159316  -1.166176
98815         NaN     96.498   -0.75917  -0.464933   2.385214
98816         NaN     96.499  -2.386887   2.186207    1.56821

[98817 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -1.212132   1.217805   3.375187
2              NaN   0.000977  -1.370485   1.744351   2.039275
3              NaN   0.001953   3.089165   2.274579  -0.801837
4              NaN    0.00293   0.120975   1.409276   -0.48534
...            ...        ...        ...        ...        ...
102396         NaN     99.995  -1.112702   3.835806   0.504633
102397         NaN     99.996  -1.624585   1.118387  -2.656656
102398         NaN     99.997   1.258904   0.621298  -3.389016
102399         NaN     99.998  -1.897099    0.41878   1.406281
102400         NaN     99.999  -4.828463  -1.234501   4.313637

[102401 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -3.554277   0.234673   1.156028
2              NaN   0.000977  -3.035028  -0.895744   2.050316
3              NaN   0.001953  -1.016954   1.600747  -0.095239
4              NaN    0.00293   -2.09596  -1.227136  -1.821252
...            ...        ...        ...        ...        ...
103420         NaN        101  -1.492011  -0.461251  -1.902216
103421         NaN        101  -3.174967  -1.506979  -2.803864
103422         NaN        101  -2.710958  -1.168222  -0.606787
103423         NaN        101  -3.300176  -1.540118  -2.215033
103424         NaN        101  -1.550933  -0.059898  -2.649296

[103425 rows x 5 columns],        Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0   0.168849   3.180385   0.294862
2             NaN   0.000977  -0.854918    1.00424  -0.051077
3             NaN   0.001953  -1.525155   1.085248  -0.437497
4             NaN    0.00293  -1.466233   1.096294   2.385214
...           ...        ...        ...        ...        ...
97788         NaN     95.495  -0.950666  -0.612219  -2.619854
97789         NaN     95.496  -4.938941   0.124209   0.235979
97790         NaN     95.497  -1.414676   0.300952  -3.826959
97791         NaN     95.498  -1.992847  -1.090897  -1.136735
97792         NaN     95.499   -2.76988   1.195712  -0.720873

[97793 rows x 5 columns],             Time         X         Y         Z
0       0.000000 -1.366802  1.280401  0.361105
1       0.000977 -0.987493  1.563926  0.788008
2       0.001953 -0.383543  2.013147  1.141307
3       0.002930  0.025227  2.462368  1.634453
4       0.003906  0.209358  2.767986  2.087118
...          ...       ...       ...       ...
65531  63.995000 -1.528837  0.613934  0.725445
65532  63.996000 -4.239244  2.259850 -1.501074
65533  63.997000 -0.328304 -2.652125  6.992820
65534  63.998000  1.196300  7.098183  1.328997
65535  63.999000  2.610425  5.794705 -1.747648

[65536 rows x 4 columns]]
Data/6.xlsx [       Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0  -0.961714  -2.247089   -4.40107
2             NaN   0.000977  -0.394591  -2.298639  -1.552597
3             NaN   0.001953   -5.44346   0.849591    5.49498
4             NaN    0.00293   -1.46255    0.77963   1.958311
...           ...        ...        ...        ...        ...
98812         NaN     96.495  -0.545578   0.021109   2.797396
98813         NaN     96.496  -2.762514   1.902683   2.955644
98814         NaN     96.497  -0.147856  -0.159316  -1.166176
98815         NaN     96.498   -0.75917  -0.464933   2.385214
98816         NaN     96.499  -2.386887   2.186207    1.56821

[98817 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -1.212132   1.217805   3.375187
2              NaN   0.000977  -1.370485   1.744351   2.039275
3              NaN   0.001953   3.089165   2.274579  -0.801837
4              NaN    0.00293   0.120975   1.409276   -0.48534
...            ...        ...        ...        ...        ...
102396         NaN     99.995  -1.112702   3.835806   0.504633
102397         NaN     99.996  -1.624585   1.118387  -2.656656
102398         NaN     99.997   1.258904   0.621298  -3.389016
102399         NaN     99.998  -1.897099    0.41878   1.406281
102400         NaN     99.999  -4.828463  -1.234501   4.313637

[102401 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -3.554277   0.234673   1.156028
2              NaN   0.000977  -3.035028  -0.895744   2.050316
3              NaN   0.001953  -1.016954   1.600747  -0.095239
4              NaN    0.00293   -2.09596  -1.227136  -1.821252
...            ...        ...        ...        ...        ...
103420         NaN        101  -1.492011  -0.461251  -1.902216
103421         NaN        101  -3.174967  -1.506979  -2.803864
103422         NaN        101  -2.710958  -1.168222  -0.606787
103423         NaN        101  -3.300176  -1.540118  -2.215033
103424         NaN        101  -1.550933  -0.059898  -2.649296

[103425 rows x 5 columns],        Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0   0.168849   3.180385   0.294862
2             NaN   0.000977  -0.854918    1.00424  -0.051077
3             NaN   0.001953  -1.525155   1.085248  -0.437497
4             NaN    0.00293  -1.466233   1.096294   2.385214
...           ...        ...        ...        ...        ...
97788         NaN     95.495  -0.950666  -0.612219  -2.619854
97789         NaN     95.496  -4.938941   0.124209   0.235979
97790         NaN     95.497  -1.414676   0.300952  -3.826959
97791         NaN     95.498  -1.992847  -1.090897  -1.136735
97792         NaN     95.499   -2.76988   1.195712  -0.720873

[97793 rows x 5 columns],             Time         X         Y         Z
0       0.000000 -1.366802  1.280401  0.361105
1       0.000977 -0.987493  1.563926  0.788008
2       0.001953 -0.383543  2.013147  1.141307
3       0.002930  0.025227  2.462368  1.634453
4       0.003906  0.209358  2.767986  2.087118
...          ...       ...       ...       ...
65531  63.995000 -1.528837  0.613934  0.725445
65532  63.996000 -4.239244  2.259850 -1.501074
65533  63.997000 -0.328304 -2.652125  6.992820
65534  63.998000  1.196300  7.098183  1.328997
65535  63.999000  2.610425  5.794705 -1.747648

[65536 rows x 4 columns],             Time         X         Y         Z
0       0.000000 -1.495694  0.267812 -0.146762
1       0.000977 -1.654046  0.348820 -0.297650
2       0.001953 -1.720333  0.326727 -0.260848
3       0.002930 -1.790303  0.311998 -0.308691
4       0.003906 -1.793986  0.370912 -0.271889
...          ...       ...       ...       ...
60923  59.495000 -3.237572 -0.851558 -1.961099
60924  59.496000 -2.718323 -1.330236  1.262754
60925  59.497000  0.316154  1.420322  3.007167
60926  59.498000  1.947554  4.491227  1.041942
60927  59.499000  1.575609  1.552879  0.810089

[60928 rows x 4 columns]]
Data/7.xlsx [       Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0  -0.961714  -2.247089   -4.40107
2             NaN   0.000977  -0.394591  -2.298639  -1.552597
3             NaN   0.001953   -5.44346   0.849591    5.49498
4             NaN    0.00293   -1.46255    0.77963   1.958311
...           ...        ...        ...        ...        ...
98812         NaN     96.495  -0.545578   0.021109   2.797396
98813         NaN     96.496  -2.762514   1.902683   2.955644
98814         NaN     96.497  -0.147856  -0.159316  -1.166176
98815         NaN     96.498   -0.75917  -0.464933   2.385214
98816         NaN     96.499  -2.386887   2.186207    1.56821

[98817 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -1.212132   1.217805   3.375187
2              NaN   0.000977  -1.370485   1.744351   2.039275
3              NaN   0.001953   3.089165   2.274579  -0.801837
4              NaN    0.00293   0.120975   1.409276   -0.48534
...            ...        ...        ...        ...        ...
102396         NaN     99.995  -1.112702   3.835806   0.504633
102397         NaN     99.996  -1.624585   1.118387  -2.656656
102398         NaN     99.997   1.258904   0.621298  -3.389016
102399         NaN     99.998  -1.897099    0.41878   1.406281
102400         NaN     99.999  -4.828463  -1.234501   4.313637

[102401 rows x 5 columns],         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0              NaN       Time          X          Y          Z
1              NaN          0  -3.554277   0.234673   1.156028
2              NaN   0.000977  -3.035028  -0.895744   2.050316
3              NaN   0.001953  -1.016954   1.600747  -0.095239
4              NaN    0.00293   -2.09596  -1.227136  -1.821252
...            ...        ...        ...        ...        ...
103420         NaN        101  -1.492011  -0.461251  -1.902216
103421         NaN        101  -3.174967  -1.506979  -2.803864
103422         NaN        101  -2.710958  -1.168222  -0.606787
103423         NaN        101  -3.300176  -1.540118  -2.215033
103424         NaN        101  -1.550933  -0.059898  -2.649296

[103425 rows x 5 columns],        Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0             NaN       Time          X          Y          Z
1             NaN          0   0.168849   3.180385   0.294862
2             NaN   0.000977  -0.854918    1.00424  -0.051077
3             NaN   0.001953  -1.525155   1.085248  -0.437497
4             NaN    0.00293  -1.466233   1.096294   2.385214
...           ...        ...        ...        ...        ...
97788         NaN     95.495  -0.950666  -0.612219  -2.619854
97789         NaN     95.496  -4.938941   0.124209   0.235979
97790         NaN     95.497  -1.414676   0.300952  -3.826959
97791         NaN     95.498  -1.992847  -1.090897  -1.136735
97792         NaN     95.499   -2.76988   1.195712  -0.720873

[97793 rows x 5 columns],             Time         X         Y         Z
0       0.000000 -1.366802  1.280401  0.361105
1       0.000977 -0.987493  1.563926  0.788008
2       0.001953 -0.383543  2.013147  1.141307
3       0.002930  0.025227  2.462368  1.634453
4       0.003906  0.209358  2.767986  2.087118
...          ...       ...       ...       ...
65531  63.995000 -1.528837  0.613934  0.725445
65532  63.996000 -4.239244  2.259850 -1.501074
65533  63.997000 -0.328304 -2.652125  6.992820
65534  63.998000  1.196300  7.098183  1.328997
65535  63.999000  2.610425  5.794705 -1.747648

[65536 rows x 4 columns],             Time         X         Y         Z
0       0.000000 -1.495694  0.267812 -0.146762
1       0.000977 -1.654046  0.348820 -0.297650
2       0.001953 -1.720333  0.326727 -0.260848
3       0.002930 -1.790303  0.311998 -0.308691
4       0.003906 -1.793986  0.370912 -0.271889
...          ...       ...       ...       ...
60923  59.495000 -3.237572 -0.851558 -1.961099
60924  59.496000 -2.718323 -1.330236  1.262754

In [36]:
merged_df = pd.concat(dataframes)
merged_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Time,X,Y,Z
0,NaN,Time,X,Y,Z,NaN,NaN,NaN,NaN
1,NaN,0,-0.961714,-2.247089,-4.40107,NaN,NaN,NaN,NaN
2,NaN,0.000977,-0.394591,-2.298639,-1.552597,NaN,NaN,NaN,NaN
3,NaN,0.001953,-5.44346,0.849591,5.49498,NaN,NaN,NaN,NaN
4,NaN,0.00293,-1.46255,0.77963,1.958311,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
18939,NaN,NaN,NaN,NaN,NaN,18.495,-3.362781,-3.635256,-1.346506
18940,NaN,NaN,NaN,NaN,NaN,18.496,-0.018964,1.722258,5.715792
18941,NaN,NaN,NaN,NaN,NaN,18.497,0.809625,5.128238,-0.102600
18942,NaN,NaN,NaN,NaN,NaN,18.498,-1.687190,-1.746318,-1.291303
18943,NaN,NaN,NaN,NaN,NaN,18.499,-2.762514,3.014689,2.068717